fragment PagesParts on Pages {
  title
  blocks {
    __typename
    ... on PagesBlocksGenericBanner {
      title
      subtitle
      image
    }
    ... on PagesBlocksGrandBanner {
      title
      subtitle
      image
      right
    }
    ... on PagesBlocksText {
      text
    }
  }
}
