fragment PagesParts on Pages {
  title
  blocks {
    __typename
    ... on PagesBlocksGenericBanner {
      title
      subtitle
      image
      imageAlt
    }
    ... on PagesBlocksGrandBanner {
      title
      subtitle
      image
      imageAlt
      right
    }
    ... on PagesBlocksText {
      text
    }
    ... on PagesBlocksInfoBox {
      title
      subtitle
      linkText
      linkTo
      outsideLink
      image
      imageAlt
      right
    }
    ... on PagesBlocksGrid {
      blocks {
        __typename
        ... on PagesBlocksGridBlocksInfoBox {
          title
          subtitle
          linkText
          linkTo
          outsideLink
          image
          imageAlt
          right
        }
        ... on PagesBlocksGridBlocksLegacyInfoBox {
          title
          subtitle
          linkText
          linkTo
          outsideLink
          image
          hoverImage
        }
      }
    }
    ... on PagesBlocksTable {
      csvData
    }
    ... on PagesBlocksLegacyInfoBox {
      title
      subtitle
      linkText
      linkTo
      outsideLink
      image
      hoverImage
    }
    ... on PagesBlocksHeadingSeparator {
      title
    }
  }
}
