//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String'];
  title?: Maybe<Scalars['String']>;
  basename: Scalars['String'];
  breadcrumbs: Array<Scalars['String']>;
  path: Scalars['String'];
  relativePath: Scalars['String'];
  extension: Scalars['String'];
  template: Scalars['String'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']>;
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean'];
  hasNextPage: Scalars['Boolean'];
  startCursor: Scalars['String'];
  endCursor: Scalars['String'];
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  id: Scalars['ID'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  pages: Pages;
  pagesConnection: PagesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<PagesFilter>;
};

export type DocumentFilter = {
  pages?: InputMaybe<PagesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String'];
  slug: Scalars['String'];
  label?: Maybe<Scalars['String']>;
  path: Scalars['String'];
  format?: Maybe<Scalars['String']>;
  matches?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<DocumentFilter>;
};

export type DocumentNode = Pages;

export type PagesBlocksGenericBanner = {
  __typename?: 'PagesBlocksGenericBanner';
  title?: Maybe<Scalars['String']>;
  subtitle?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type PagesBlocksGrandBanner = {
  __typename?: 'PagesBlocksGrandBanner';
  title?: Maybe<Scalars['String']>;
  subtitle?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
  right?: Maybe<Scalars['Boolean']>;
};

export type PagesBlocksText = {
  __typename?: 'PagesBlocksText';
  text?: Maybe<Scalars['JSON']>;
};

export type PagesBlocksInfoBox = {
  __typename?: 'PagesBlocksInfoBox';
  title?: Maybe<Scalars['String']>;
  subtitle?: Maybe<Scalars['String']>;
  linkText?: Maybe<Scalars['String']>;
  linkTo?: Maybe<Scalars['String']>;
  outsideLink?: Maybe<Scalars['Boolean']>;
  image?: Maybe<Scalars['String']>;
  right?: Maybe<Scalars['Boolean']>;
};

export type PagesBlocksGridBlocksInfoBox = {
  __typename?: 'PagesBlocksGridBlocksInfoBox';
  title?: Maybe<Scalars['String']>;
  subtitle?: Maybe<Scalars['String']>;
  linkText?: Maybe<Scalars['String']>;
  linkTo?: Maybe<Scalars['String']>;
  outsideLink?: Maybe<Scalars['Boolean']>;
  image?: Maybe<Scalars['String']>;
  right?: Maybe<Scalars['Boolean']>;
};

export type PagesBlocksGridBlocks = PagesBlocksGridBlocksInfoBox;

export type PagesBlocksGrid = {
  __typename?: 'PagesBlocksGrid';
  blocks?: Maybe<Array<Maybe<PagesBlocksGridBlocks>>>;
};

export type PagesBlocksTable = {
  __typename?: 'PagesBlocksTable';
  csvData?: Maybe<Scalars['String']>;
};

export type PagesBlocks = PagesBlocksGenericBanner | PagesBlocksGrandBanner | PagesBlocksText | PagesBlocksInfoBox | PagesBlocksGrid | PagesBlocksTable;

export type Pages = Node & Document & {
  __typename?: 'Pages';
  title?: Maybe<Scalars['String']>;
  blocks?: Maybe<Array<Maybe<PagesBlocks>>>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']>;
  eq?: InputMaybe<Scalars['String']>;
  exists?: InputMaybe<Scalars['Boolean']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']>;
  eq?: InputMaybe<Scalars['String']>;
  exists?: InputMaybe<Scalars['Boolean']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
};

export type PagesBlocksGenericBannerFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']>;
  exists?: InputMaybe<Scalars['Boolean']>;
};

export type PagesBlocksGrandBannerFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  right?: InputMaybe<BooleanFilter>;
};

export type PagesBlocksTextTextInfoBoxFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  linkText?: InputMaybe<StringFilter>;
  linkTo?: InputMaybe<StringFilter>;
  outsideLink?: InputMaybe<BooleanFilter>;
  image?: InputMaybe<ImageFilter>;
  right?: InputMaybe<BooleanFilter>;
};

export type PagesBlocksTextTextFilter = {
  infoBox?: InputMaybe<PagesBlocksTextTextInfoBoxFilter>;
};

export type PagesBlocksTextFilter = {
  text?: InputMaybe<PagesBlocksTextTextFilter>;
};

export type PagesBlocksInfoBoxFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  linkText?: InputMaybe<StringFilter>;
  linkTo?: InputMaybe<StringFilter>;
  outsideLink?: InputMaybe<BooleanFilter>;
  image?: InputMaybe<ImageFilter>;
  right?: InputMaybe<BooleanFilter>;
};

export type PagesBlocksGridBlocksInfoBoxFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  linkText?: InputMaybe<StringFilter>;
  linkTo?: InputMaybe<StringFilter>;
  outsideLink?: InputMaybe<BooleanFilter>;
  image?: InputMaybe<ImageFilter>;
  right?: InputMaybe<BooleanFilter>;
};

export type PagesBlocksGridBlocksFilter = {
  InfoBox?: InputMaybe<PagesBlocksGridBlocksInfoBoxFilter>;
};

export type PagesBlocksGridFilter = {
  blocks?: InputMaybe<PagesBlocksGridBlocksFilter>;
};

export type PagesBlocksTableFilter = {
  csvData?: InputMaybe<StringFilter>;
};

export type PagesBlocksFilter = {
  GenericBanner?: InputMaybe<PagesBlocksGenericBannerFilter>;
  GrandBanner?: InputMaybe<PagesBlocksGrandBannerFilter>;
  text?: InputMaybe<PagesBlocksTextFilter>;
  InfoBox?: InputMaybe<PagesBlocksInfoBoxFilter>;
  Grid?: InputMaybe<PagesBlocksGridFilter>;
  Table?: InputMaybe<PagesBlocksTableFilter>;
};

export type PagesFilter = {
  title?: InputMaybe<StringFilter>;
  blocks?: InputMaybe<PagesBlocksFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updatePages: Pages;
  createPages: Pages;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String'];
  relativePath: Scalars['String'];
  template?: InputMaybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String'];
  params: PagesMutation;
};

export type DocumentMutation = {
  pages?: InputMaybe<PagesMutation>;
};

export type PagesBlocksGenericBannerMutation = {
  title?: InputMaybe<Scalars['String']>;
  subtitle?: InputMaybe<Scalars['String']>;
  image?: InputMaybe<Scalars['String']>;
};

export type PagesBlocksGrandBannerMutation = {
  title?: InputMaybe<Scalars['String']>;
  subtitle?: InputMaybe<Scalars['String']>;
  image?: InputMaybe<Scalars['String']>;
  right?: InputMaybe<Scalars['Boolean']>;
};

export type PagesBlocksTextMutation = {
  text?: InputMaybe<Scalars['JSON']>;
};

export type PagesBlocksInfoBoxMutation = {
  title?: InputMaybe<Scalars['String']>;
  subtitle?: InputMaybe<Scalars['String']>;
  linkText?: InputMaybe<Scalars['String']>;
  linkTo?: InputMaybe<Scalars['String']>;
  outsideLink?: InputMaybe<Scalars['Boolean']>;
  image?: InputMaybe<Scalars['String']>;
  right?: InputMaybe<Scalars['Boolean']>;
};

export type PagesBlocksGridBlocksInfoBoxMutation = {
  title?: InputMaybe<Scalars['String']>;
  subtitle?: InputMaybe<Scalars['String']>;
  linkText?: InputMaybe<Scalars['String']>;
  linkTo?: InputMaybe<Scalars['String']>;
  outsideLink?: InputMaybe<Scalars['Boolean']>;
  image?: InputMaybe<Scalars['String']>;
  right?: InputMaybe<Scalars['Boolean']>;
};

export type PagesBlocksGridBlocksMutation = {
  InfoBox?: InputMaybe<PagesBlocksGridBlocksInfoBoxMutation>;
};

export type PagesBlocksGridMutation = {
  blocks?: InputMaybe<Array<InputMaybe<PagesBlocksGridBlocksMutation>>>;
};

export type PagesBlocksTableMutation = {
  csvData?: InputMaybe<Scalars['String']>;
};

export type PagesBlocksMutation = {
  GenericBanner?: InputMaybe<PagesBlocksGenericBannerMutation>;
  GrandBanner?: InputMaybe<PagesBlocksGrandBannerMutation>;
  text?: InputMaybe<PagesBlocksTextMutation>;
  InfoBox?: InputMaybe<PagesBlocksInfoBoxMutation>;
  Grid?: InputMaybe<PagesBlocksGridMutation>;
  Table?: InputMaybe<PagesBlocksTableMutation>;
};

export type PagesMutation = {
  title?: InputMaybe<Scalars['String']>;
  blocks?: InputMaybe<Array<InputMaybe<PagesBlocksMutation>>>;
};

export type PagesPartsFragment = { __typename?: 'Pages', title?: string | null, blocks?: Array<{ __typename: 'PagesBlocksGenericBanner', title?: string | null, subtitle?: string | null, image?: string | null } | { __typename: 'PagesBlocksGrandBanner', title?: string | null, subtitle?: string | null, image?: string | null, right?: boolean | null } | { __typename: 'PagesBlocksText', text?: any | null } | { __typename: 'PagesBlocksInfoBox', title?: string | null, subtitle?: string | null, linkText?: string | null, linkTo?: string | null, outsideLink?: boolean | null, image?: string | null, right?: boolean | null } | { __typename: 'PagesBlocksGrid', blocks?: Array<{ __typename: 'PagesBlocksGridBlocksInfoBox', title?: string | null, subtitle?: string | null, linkText?: string | null, linkTo?: string | null, outsideLink?: boolean | null, image?: string | null, right?: boolean | null } | null> | null } | { __typename: 'PagesBlocksTable', csvData?: string | null } | null> | null };

export type PagesQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type PagesQuery = { __typename?: 'Query', pages: { __typename?: 'Pages', id: string, title?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'PagesBlocksGenericBanner', title?: string | null, subtitle?: string | null, image?: string | null } | { __typename: 'PagesBlocksGrandBanner', title?: string | null, subtitle?: string | null, image?: string | null, right?: boolean | null } | { __typename: 'PagesBlocksText', text?: any | null } | { __typename: 'PagesBlocksInfoBox', title?: string | null, subtitle?: string | null, linkText?: string | null, linkTo?: string | null, outsideLink?: boolean | null, image?: string | null, right?: boolean | null } | { __typename: 'PagesBlocksGrid', blocks?: Array<{ __typename: 'PagesBlocksGridBlocksInfoBox', title?: string | null, subtitle?: string | null, linkText?: string | null, linkTo?: string | null, outsideLink?: boolean | null, image?: string | null, right?: boolean | null } | null> | null } | { __typename: 'PagesBlocksTable', csvData?: string | null } | null> | null } };

export type PagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<PagesFilter>;
}>;


export type PagesConnectionQuery = { __typename?: 'Query', pagesConnection: { __typename?: 'PagesConnection', totalCount: number, edges?: Array<{ __typename?: 'PagesConnectionEdges', node?: { __typename?: 'Pages', id: string, title?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'PagesBlocksGenericBanner', title?: string | null, subtitle?: string | null, image?: string | null } | { __typename: 'PagesBlocksGrandBanner', title?: string | null, subtitle?: string | null, image?: string | null, right?: boolean | null } | { __typename: 'PagesBlocksText', text?: any | null } | { __typename: 'PagesBlocksInfoBox', title?: string | null, subtitle?: string | null, linkText?: string | null, linkTo?: string | null, outsideLink?: boolean | null, image?: string | null, right?: boolean | null } | { __typename: 'PagesBlocksGrid', blocks?: Array<{ __typename: 'PagesBlocksGridBlocksInfoBox', title?: string | null, subtitle?: string | null, linkText?: string | null, linkTo?: string | null, outsideLink?: boolean | null, image?: string | null, right?: boolean | null } | null> | null } | { __typename: 'PagesBlocksTable', csvData?: string | null } | null> | null } | null } | null> | null } };

export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  title
  blocks {
    __typename
    ... on PagesBlocksGenericBanner {
      title
      subtitle
      image
    }
    ... on PagesBlocksGrandBanner {
      title
      subtitle
      image
      right
    }
    ... on PagesBlocksText {
      text
    }
    ... on PagesBlocksInfoBox {
      title
      subtitle
      linkText
      linkTo
      outsideLink
      image
      right
    }
    ... on PagesBlocksGrid {
      blocks {
        __typename
        ... on PagesBlocksGridBlocksInfoBox {
          title
          subtitle
          linkText
          linkTo
          outsideLink
          image
          right
        }
      }
    }
    ... on PagesBlocksTable {
      csvData
    }
  }
}
    `;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    totalCount
    edges {
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (client: TinaClient) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: any,
    client
  ) => Promise<any> = async (doc, vars, _options) => {
    const data = await client.request({
      query: doc,
      variables: vars,
    });

    return { data: data?.data, query: doc, variables: vars || {} };
  };

  return requester;
};

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(createClient({ url: "http://localhost:4001/graphql", queries }))
  );

export const queries = (client: TinaClient) => {
  const requester = generateRequester(client);
  return getSdk(requester);
};

  