import { Footer, NavBar, ThemeProvider } from "@czb-ui/core";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import { NavBarAndFooterPlacer } from "@czb-ui/core";

import "@fontsource/hanken-grotesk/400.css";
import "@fontsource/hanken-grotesk/600.css";
import "@fontsource/hanken-grotesk/700.css";
import "@fontsource/stix-two-text/600.css";
import "@fontsource/lato/700.css";
import "@fontsource/barlow/600.css";
import "@fontsource/barlow/400.css";
import "@fontsource/jetbrains-mono/400.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider>
            <NavBarAndFooterPlacer topBar={<NavBar />} bottomBar={<Footer />}>
              {children}
            </NavBarAndFooterPlacer>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
