name: changeset Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Run changeset status
        run: yarn changeset status --since origin/main
