name: changeset Check
on: [push]
jobs:
  changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Pull origin/main for changesets
        run: git pull -f origin main:main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Run changeset status
        run: yarn changeset status
